DELETE EMPRESAS
DELETE USUARIO
DELETE USUARIO_EMPRESA
DELETE CLIENTE
DELETE PAIS
DELETE PROVEEDOR
DELETE MARCA
DELETE CATEGORIA
DELETE TIPO_PRODUCTO
DELETE UNIDAD_MEDIDA
TRUNCATE TABLE PRODUCTOS
TRUNCATE TABLE BODEGA
TRUNCATE TABLE PEB
TRUNCATE TABLE MIGRAR_INVENTARIO