ALTER PROCEDURE SP_MIGRAR_INVENTARIO
AS
DECLARE @BODEGA NVARCHAR(100)
DECLARE @CODIGO NVARCHAR(30)
DECLARE @CODIGO_BARRA NVARCHAR(100)
DECLARE @PRODUCTO NVARCHAR(100)
DECLARE @MARCA NVARCHAR(100)
DECLARE @CATEGORIA NVARCHAR(100)
DECLARE @TIPO NVARCHAR(100)
DECLARE @UDM NVARCHAR(100)
DECLARE @FOB FLOAT
DECLARE @CIF FLOAT
DECLARE @PRECIO FLOAT
DECLARE @EXISTENCIAS FLOAT
DECLARE @RACK NVARCHAR(10)
DECLARE @COLUMNA NVARCHAR(10)
DECLARE @FILA NVARCHAR(10)
DECLARE @MINIMO FLOAT
DECLARE @MAXIMO FLOAT
DECLARE @CLASIFICACION NVARCHAR(3)
DECLARE @SERVICIO NVARCHAR(1)
DECLARE @IMPUESTO NVARCHAR(1)
DECLARE @ACTIVO NVARCHAR(1)
DECLARE @LOCAL NVARCHAR(1)
DECLARE RP CURSOR FOR
SELECT
BODEGA,
CODIGO,
CODIGO_BARRA,
PRODUCTO,
MARCA,
CATEGORIA,
TIPO,
UDM,
FOB,
CIF,
PRECIO,
EXISTENCIAS,
RACK,
COLUMNA,
FILA,
MINIMO,
MAXIMO,
CLASIFICACION,
SERVICIO,
IMPUESTO,
ACTIVO,
LOCAL
FROM MIGRAR_INVENTARIO
OPEN RP
FETCH NEXT FROM RP INTO
@BODEGA,
@CODIGO,
@CODIGO_BARRA,
@PRODUCTO,
@MARCA,
@CATEGORIA,
@TIPO,
@UDM,
@FOB,
@CIF,
@PRECIO,
@EXISTENCIAS,
@RACK,
@COLUMNA,
@FILA,
@MINIMO,
@MAXIMO,
@CLASIFICACION,
@SERVICIO,
@IMPUESTO,
@ACTIVO,
@LOCAL
WHILE(@@FETCH_STATUS=0)
  BEGIN
  IF NOT EXISTS (SELECT DESCRIPCION FROM BODEGA WHERE DESCRIPCION = @BODEGA)
    INSERT BODEGA (DESCRIPCION, ACTIVO) VALUES (@BODEGA,0)

  IF NOT EXISTS (SELECT NOMBRE FROM MARCA WHERE NOMBRE = @MARCA)
    INSERT MARCA (NOMBRE) VALUES (@MARCA)

  IF NOT EXISTS (SELECT NOMBRE FROM CATEGORIA WHERE NOMBRE = @CATEGORIA)
    INSERT CATEGORIA (NOMBRE) VALUES (@CATEGORIA)

  IF NOT EXISTS (SELECT NOMBRE FROM TIPO_PRODUCTO WHERE NOMBRE = @TIPO)
    INSERT TIPO_PRODUCTO (NOMBRE) VALUES (@TIPO)

  IF NOT EXISTS (SELECT NOMBRE FROM UNIDAD_MEDIDA WHERE NOMBRE = @UDM)
    INSERT UNIDAD_MEDIDA (NOMBRE) VALUES (@UDM)

  IF NOT EXISTS (SELECT CODIGO_COMPUESTO FROM PRODUCTOS WHERE CODIGO_COMPUESTO = @CODIGO)
    INSERT PRODUCTOS (
      CODIGO_COMPUESTO,
      CODIGO_BARRA,
      PRODUCTO,
      MARCA,
      CATEGORIA,
      TIPO,
      UDM,
      FOB,
      CIF,
      MINIMO,
      MAXIMO,
      CLASIFICACION,
      SERVICIO,
      IMPUESTO,
      LOCAL,
      ACTIVO)
      VALUES(
      @CODIGO,
      @CODIGO_BARRA,
      @PRODUCTO,
      (SELECT ID_MARCA FROM MARCA WHERE NOMBRE = @MARCA),
      (SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE = @CATEGORIA),
      (SELECT ID_TIPO FROM TIPO_PRODUCTO WHERE NOMBRE = @TIPO),
      (SELECT ID_UDM FROM UNIDAD_MEDIDA WHERE NOMBRE = @UDM),
      @FOB,
      @CIF,
      @MINIMO,
      @MAXIMO,
      @CLASIFICACION,
      @SERVICIO,
      @IMPUESTO,
      @LOCAL,
      @ACTIVO)
    END
  FETCH NEXT FROM RP INTO
  @BODEGA,
  @CODIGO,
  @CODIGO_BARRA,
  @PRODUCTO,
  @MARCA,
  @CATEGORIA,
  @TIPO,
  @UDM,
  @FOB,
  @CIF,
  @PRECIO,
  @EXISTENCIAS,
  @RACK,
  @COLUMNA,
  @FILA,
  @MINIMO,
  @MAXIMO,
  @CLASIFICACION,
  @SERVICIO,
  @IMPUESTO,
  @ACTIVO,
  @LOCAL
CLOSE RP
DEALLOCATE RP
GO
